config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  get 'static_pages/new'

  resources :users

  resources :sessions, only: [:new, :create]
  match '/signup',   to: 'users#new', via: 'get'
  match '/signin',   to: 'sessions#new', via: 'get'
  match '/signout',   to: 'sessions#destroy', via: 'delete'

  resources :acceptors, only: [:index, :show]
  resources :payers, only: [:index, :show]
  resources :services, only: [:index]
  resources :pdf_files

  resources :operations do
    collection do
      get 'table'
      get 'chart'
    end
  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Komplateg by Dush
  %nav
    %ul
      %li=link_to 'About',   about_path
      %li
        %a{href: 'http://osi.in.ua/'}News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      =link_to 'Komplateg', root_path, id: 'logo'
      %nav
        %ul.nav.pull-right
          %li=link_to 'Home', root_path
          %li=link_to 'Help', help_path
          -if signed_in?
            %li=link_to 'Users', users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{href: '#', 'data-toggle': 'dropdown'}
                Account
                %b.caret
              %ul.dropdown-menu
                %li=link_to 'Profile', current_user
                %li=link_to 'Settings', edit_user_path(current_user)
                %li.divider
                %li=link_to 'Sign out', signout_path, method: 'delete'
          -else
            %li=link_to 'Sign in', signin_path
-if signed_in?
  .menu-base.center
    =render 'layouts/menu_base'

app/views/layouts/_menu_base.html.haml
=link_to 'Operations', table_operations_path
|
=link_to 'Payers', payers_path
|
=link_to 'Acceptors', acceptors_path
|
=link_to 'Services', services_path
%br
=link_to 'Table', table_operations_path
|
=link_to 'Chart', chart_operations_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      #{full_title(yield(:title))}
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      -flash.each do |key, value|
        =content_tag :div, value, class:"alert alert-#{key}"
      = yield
      = render 'layouts/footer'
      =debug(params) if Rails.env.development?